- name: Install Xorg and tools
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xfd
      - xorg-xprop
      - xorg-xkill
      - xorg-xauth
      - xautomation
      - xbindkeys

- name: Install i3 and i3lock
  become: yes
  pacman:
    name:
      - i3-gaps
      - i3lock

- name: Ensure i3 config dir exists
  file:
    path: ~/.config/i3
    state: directory

- name: Install polybar
  yay:
    name: polybar

- name: Ensure polybar config dir exists
  file:
    path: ~/.config/polybar
    state: directory

- name: Install rofi
  become: yes
  pacman:
    name: rofi

- name: Install rofi-calc
  yay:
    name: rofi-calc

- name: Ensure rofi config dir exists
  file:
    path: ~/.config/rofi
    state: directory

- name: Install alacritty
  become: yes
  pacman:
    name: alacritty

- name: Ensure alacritty config dir exists
  file:
    path: ~/.config/alacritty
    state: directory

- name: Install pcman
  become: yes
  pacman:
    name: pcmanfm

- name: Install xarchiver
  yay:
    name: xarchiver

- name: Install screen utilities
  become: yes
  pacman:
    name:
      - scrot
      - feh
      - lxappearance
      - lxrandr

- name: Install autorandr
  yay:
    name: autorandr

- name: Install polkit
  yay:
    name: polkit

- name: Install arc-gtk-theme
  become: yes
  pacman:
    name:
      - arc-gtk-theme

- name: Ensure gtk-3.0 config dir exists
  file:
    path: ~/.config/gtk-3.0
    state: directory

- name: Configure two keyboard layouts
  become: yes
  shell: localectl --no-convert set-x11-keymap br,us pc104 abnt2, grp:alt_shift_toggle
