- name: Setup global git config
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { name: "user.name",   value: "Caio Augusto Sabino Correa" }
#    - { name: "user.email",  value: "caio.correa@ifood.com.br" }
    - { name: "user.email",  value: "correadvl@gmail.com" }
    - { name: "core.editor", value: "vim" }
    - { name: "pull.rebase", value: "false" }
    - { name: "ui.color",    value: "true" }
